# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: fcollonval@gmail.com
author_name: Frederic Collonval
has_binder: true
has_settings: true
kind: server
labextension_name: jupyterlab-search-replace
project_short_description: Search and replace across files
python_name: jupyterlab_search_replace
repository: https://github.com/jupyterlab-contrib/search-replace.git.git
test: true

