# a mybinder.org-ready environment for demoing jupyterlab_search_replace
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate search-replace-demo
#
name: search-replace-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - jupyterlab >=3,<4.0.0a0
  - ripgrep
  # labextension build dependencies
  - nodejs =18
